### ISSUE TITLE
What's the speedup of quantized models

### ISSUE THREAD

**Issue by hiyijian** [anson0910/CNN_face_detection_models#1]
hi @anson0910 ,
Would you please tell us the speedup of quantized models compared to orignal caffe model?
And how to get these quantized models?
Thanks

**Comment by anson0910** [comment]
The quantized models do not speed up the performance in software implementation, but rather benefit mainly in hardware with less memory storage, less area and little acceleration.
I think most people here are not interested in hardware (ASIC, FPGA) related issues, so I didn't put any documentation, but if you're still interested, I can say more!
